name: Performance Audit

on:
  deployment_status:

jobs:
  audit:
    if: github.event.deployment_status.state == 'success'
    uses: tikisen/tikisen/.github/workflows/audit-psi.yml@main
    with:
      site_url: ${{ github.event.deployment_status.environment_url }}
    secrets: inherit
